export const Spacing = {
  page: {
    "data-gap": "6",
    "data-md-m": "2",
    "data-md-mb": "8",
    "data-md-mt": "0",
    "data-md-pt": "2",
    "data-md-px": "0",
    "data-pb": "16",
    "data-pt": "6",
    "data-px": "3",
  },
  navigation: { "data-px": "2", "data-py": "4" },
  header: { "data-gap": "3" },
  block: { "data-gap": "4" },
  columns: { "data-gap": "3", "data-md-gap": "6" },
  labelled: { "data-gap": "2" },
  toolbar: { "data-gap": "2" },
  chips: { "data-gap": "2" },
  cards: { "data-gap": "2" },
  tiles: { "data-gap": "3" },
  surface: { "data-p": "4" },
  surfaceCompact: { "data-p": "3" },
  empty: { "data-gap": "1", "data-px": "4", "data-py": "8" },
  tile: { "data-md-py": "3", "data-p": "4" },
  row: { "data-gap": "3" },
  lines: { "data-gap": "1" },
  controls: { "data-gap": "1" },
  icon: { "data-gap": "2" },
  iconTight: { "data-gap": "1" },
  dialog: { "data-gap": "8", "data-md-mt": "4", "data-md-p": "3", "data-mt": "12" },
  form: { "data-gap": "6" },
  field: { "data-gap": "1-5" },
} as const;
