export const Spacing = {
  page: {
    "data-gap": "6",
    "data-md-m": "2",
    "data-md-mb": "8",
    "data-md-mt": "0",
    "data-md-pt": "2",
    "data-md-px": "0",
    "data-pb": "16",
    "data-pt": "6",
    "data-px": "3",
  },
  navigation: { "data-px": "2", "data-py": "4" },
  dialog: { "data-gap": "8", "data-md-mt": "4", "data-md-p": "3", "data-mt": "12" },
  empty: { "data-gap": "1", "data-px": "4", "data-py": "8" },
  tile: { "data-md-py": "3", "data-p": "4" },
  grid: { "data-gap": "6", "data-md-gap": "3" },
  columns: { "data-gap": "3", "data-md-gap": "6" },
  rowCompact: { "data-gap": "3", "data-py": "1-5" },
  surface: { "data-p": "4" },
  surfaceCompact: { "data-p": "3" },
  field: { "data-gap": "1-5" },
  inline: { "data-gap": "1" },
  cluster: { "data-gap": "2" },
  related: { "data-gap": "3" },
  block: { "data-gap": "4" },
  section: { "data-gap": "6" },
  stack: { "data-gap": "8" },
} as const;
